dependencies:
  - "OpenZeppelin/openzeppelin-contracts@5.2.0"
compiler:
  solc:
    remappings:
    - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.2.0"
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
